# 1. Onde está o banco? (O endereço)
spring.datasource.url=jdbc:sqlite:estoque.db

# 2. Qual é o "motor" (driver) que o Java deve usar?
spring.datasource.driver-class-name=org.sqlite.JDBC

# 3. Qual o dialeto (a língua) que o banco fala?
# Como o SQLite é um banco mais simples, avisamos ao Hibernate (o tradutor do Java) como falar com ele.
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 4. O que o Java deve fazer com as tabelas?
# "update" significa: "Se a tabela não existir, crie. Se eu adicionar uma coluna nova, atualize."
spring.jpa.hibernate.ddl-auto=update